# Generated by Django 5.1.3 on 2025-11-18 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["organization_id", "order"],
                "unique_together": {("organization_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="TimetableVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(db_index=True, max_length=100)),
                ("variant_number", models.IntegerField()),
                (
                    "optimization_priority",
                    models.CharField(
                        choices=[
                            ("balanced", "Balanced - All constraints equally weighted"),
                            ("room_utilization", "Maximize Room Utilization"),
                            ("faculty_balance", "Minimize Faculty Workload Variance"),
                            (
                                "student_compact",
                                "Maximize Student Schedule Compactness",
                            ),
                            (
                                "faculty_preference",
                                "Maximize Faculty Preference Satisfaction",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("organization_id", models.CharField(max_length=100)),
                ("department_id", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
                ("academic_year", models.CharField(max_length=20)),
                ("timetable_entries", models.JSONField()),
                ("statistics", models.JSONField()),
                ("quality_metrics", models.JSONField()),
                ("is_selected", models.BooleanField(default=False)),
                ("selected_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_variants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["job_id", "variant_number"],
            },
        ),
        migrations.CreateModel(
            name="TimetableWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("organization_id", models.CharField(max_length=100)),
                ("department_id", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
                ("academic_year", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_for_review_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("timetable_entries", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflow_timetables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_workflow_timetables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_workflow_timetables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.timetablevariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimetableReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("suggested_changes", models.JSONField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="academics.timetableworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="FixedSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(max_length=100)),
                (
                    "department_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("event_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_blocked", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["organization_id", "is_active"],
                        name="academics_f_organiz_f9e7a7_idx",
                    ),
                    models.Index(
                        fields=["day", "start_time"], name="academics_f_day_409c5c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="timetablevariant",
            index=models.Index(
                fields=["job_id", "is_selected"], name="academics_t_job_id_22fa7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetablevariant",
            index=models.Index(
                fields=["organization_id", "department_id", "semester"],
                name="academics_t_organiz_39a94d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetablevariant",
            unique_together={("job_id", "variant_number")},
        ),
        migrations.AddIndex(
            model_name="timetableworkflow",
            index=models.Index(
                fields=["status", "organization_id"],
                name="academics_t_status_605672_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableworkflow",
            index=models.Index(
                fields=["department_id", "semester", "academic_year"],
                name="academics_t_departm_cdc716_idx",
            ),
        ),
    ]
